# -*- coding: utf-8 -*-
"""translator_DSP461

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xCRzhuUCJT71TUjbSKKDzAC1dk1epx5J
"""

# %%writefile translator.py

"""
translator.py

Translate coded dataset fields into human-readable labels.

Usage:
    - import translator
    - translator.translate_dataframe(df)  # returns a new DataFrame with translated columns
    - translator.translate_value('Marital Status', 1)  # returns 'single'
"""

from typing import Any, Dict
import pandas as pd

# ---------------------------
# Mapping dictionaries
# ---------------------------

MARITAL_STATUS = {
    1: "single",
    2: "married",
    3: "widower",
    4: "divorced",
    5: "facto union",
    6: "legally separated",
}

APPLICATION_MODE = {
    1: "1st phase - general contingent",
    2: "Ordinance No. 612/93",
    5: "1st phase - special contingent (Azores Island)",
    7: "Holders of other higher courses",
    10: "Ordinance No. 854-B/99",
    15: "International student (bachelor)",
    16: "1st phase - special contingent (Madeira Island)",
    17: "2nd phase - general contingent",
    18: "3rd phase - general contingent",
    26: "Ordinance No. 533-A/99, item b2) (Different Plan)",
    27: "Ordinance No. 533-A/99, item b3 (Other Institution)",
    39: "Over 23 years old",
    42: "Transfer",
    43: "Change of course",
    44: "Technological specialization diploma holders",
    51: "Change of institution/course",
    53: "Short cycle diploma holders",
    57: "Change of institution/course (International)",
}

# sample Course mapping (use more codes as needed)
COURSE = {
    33: "Biofuel Production Technologies",
    171: "Animation and Multimedia Design",
    8014: "Social Service (evening attendance)",
    9003: "Agronomy",
    9070: "Communication Design",
    9085: "Veterinary Nursing",
    9119: "Informatics Engineering",
    9130: "Equinculture",
    9147: "Management",
    9238: "Social Service",
    9254: "Tourism",
    9500: "Nursing",
    9556: "Oral Hygiene",
    9670: "Advertising and Marketing Management",
    9773: "Journalism and Communication",
    9853: "Basic Education",
    9991: "Management (evening attendance)",
}

DAYTIME_EVENING = {
    1: "daytime",
    0: "evening",
}

PREVIOUS_QUALIFICATION = {
    1: "Secondary education",
    2: "Higher education - bachelor's degree",
    3: "Higher education - degree",
    4: "Higher education - master's",
    5: "Higher education - doctorate",
    6: "Frequency of higher education",
    9: "12th year of schooling - not completed",
    10: "11th year of schooling - not completed",
    12: "Other - 11th year of schooling",
    14: "10th year of schooling",
    15: "10th year of schooling - not completed",
    19: "Basic education 3rd cycle (9th/10th/11th year) or equiv.",
    38: "Basic education 2nd cycle (6th/7th/8th year) or equiv.",
    39: "Technological specialization course",
    40: "Higher education - degree (1st cycle)",
    42: "Professional higher technical course",
    43: "Higher education - master (2nd cycle)",
}

# Previous qualification (grade) and Admission grade are numeric (0-200) - keep numeric.

NATIONALITY = {
    1: "Portuguese",
    2: "German",
    6: "Spanish",
    11: "Italian",
    13: "Dutch",
    14: "English",
    17: "Lithuanian",
    21: "Angolan",
    22: "Cape Verdean",
    24: "Guinean",
    25: "Mozambican",
    26: "Santomean",
    32: "Turkish",
    41: "Brazilian",
    62: "Romanian",
    100: "Moldova (Republic of)",
    101: "Mexican",
    103: "Ukrainian",
    105: "Russian",
    108: "Cuban",
    109: "Colombian",
}

MOTHER_QUALIFICATION = {
    1: "Secondary Education - 12th Year or Eq.",
    2: "Higher Education - Bachelor's Degree",
    3: "Higher Education - Degree",
    4: "Higher Education - Master's",
    5: "Higher Education - Doctorate",
    6: "Frequency of Higher Education",
    9: "12th Year - Not Completed",
    10: "11th Year - Not Completed",
    11: "7th Year (Old)",
    12: "Other - 11th Year",
    14: "10th Year",
    18: "General commerce course",
    19: "Basic Education 3rd Cycle (9th/10th/11th Year) or Equiv.",
    22: "Technical-professional course",
    26: "7th year of schooling",
    27: "2nd cycle of the general high school course",
    29: "9th Year - Not Completed",
    30: "8th year of schooling",
    34: "Unknown",
    35: "Can't read or write",
    36: "Can read without having a 4th year of schooling",
    37: "Basic education 1st cycle (4th/5th year) or equiv.",
    38: "Basic Education 2nd Cycle (6th/7th/8th Year) or Equiv.",
    39: "Technological specialization course",
    40: "Higher education - degree (1st cycle)",
    41: "Specialized higher studies course",
    42: "Professional higher technical course",
    43: "Higher Education - Master (2nd cycle)",
    44: "Higher Education - Doctorate (3rd cycle)",
}

FATHER_QUALIFICATION = {
    1: "Secondary Education - 12th Year or Eq.",
    2: "Higher Education - Bachelor's Degree",
    3: "Higher Education - Degree",
    4: "Higher Education - Master's",
    5: "Higher Education - Doctorate",
    6: "Frequency of Higher Education",
    9: "12th Year - Not Completed",
    10: "11th Year - Not Completed",
    11: "7th Year (Old)",
    12: "Other - 11th Year",
    13: "2nd year complementary high school course",
    14: "10th Year",
    18: "General commerce course",
    19: "Basic Education 3rd Cycle (9th/10th/11th Year) or Equiv.",
    20: "Complementary High School Course",
    22: "Technical-professional course",
    25: "Complementary High School Course - not concluded",
    26: "7th year of schooling",
    27: "2nd cycle of the general high school course",
    29: "9th Year - Not Completed",
    30: "8th year of schooling",
    31: "General Course of Administration and Commerce",
    33: "Supplementary Accounting and Administration",
    34: "Unknown",
    35: "Can't read or write",
    36: "Can read without having a 4th year of schooling",
    37: "Basic education 1st cycle (4th/5th year) or equiv.",
    38: "Basic Education 2nd Cycle (6th/7th/8th Year) or Equiv.",
    39: "Technological specialization course",
    40: "Higher education - degree (1st cycle)",
    41: "Specialized higher studies course",
    42: "Professional higher technical course",
    43: "Higher Education - Master (2nd cycle)",
    44: "Higher Education - Doctorate (3rd cycle)",
}

# Occupations: we'll include all codes provided (mother and father separate dictionaries, but many overlaps)
MOTHER_OCCUPATION = {
    0: "Student",
    1: "Representatives of Legislative/Executive, Directors, Exec Managers",
    2: "Specialists in Intellectual and Scientific Activities",
    3: "Intermediate Level Technicians and Professions",
    4: "Administrative staff",
    5: "Personal Services, Security and Safety Workers and Sellers",
    6: "Farmers and Skilled Workers in Agriculture, Fisheries and Forestry",
    7: "Skilled Workers in Industry, Construction and Craftsmen",
    8: "Installation and Machine Operators and Assembly Workers",
    9: "Unskilled Workers",
    10: "Armed Forces Professions",
    90: "Other Situation",
    99: "(blank)",
    122: "Health professionals",
    123: "teachers",
    125: "Specialists in information and communication technologies (ICT)",
    131: "Intermediate level science and engineering technicians and professions",
    132: "Technicians and professionals, intermediate level of health",
    134: "Intermediate level technicians from legal, social, sports, cultural services",
    141: "Office workers, secretaries, data processing operators",
    143: "Data, accounting, statistical, financial services and registry operators",
    144: "Other administrative support staff",
    151: "personal service workers",
    152: "sellers",
    153: "Personal care workers and the like",
    171: "Skilled construction workers etc. (except electricians)",
    173: "Skilled workers in printing, precision instrument manufacturing, jewelers, artisans",
    175: "Workers in food processing, woodworking, clothing and other industries",
    191: "cleaning workers",
    192: "Unskilled workers in agriculture, animal production, fisheries and forestry",
    193: "Unskilled workers in extractive industry, construction, manufacturing and transport",
    194: "Meal preparation assistants",
}

FATHER_OCCUPATION = {
    0: "Student",
    1: "Representatives of Legislative/Executive, Directors, Exec Managers",
    2: "Specialists in Intellectual and Scientific Activities",
    3: "Intermediate Level Technicians and Professions",
    4: "Administrative staff",
    5: "Personal Services, Security and Safety Workers and Sellers",
    6: "Farmers and Skilled Workers in Agriculture, Fisheries and Forestry",
    7: "Skilled Workers in Industry, Construction and Craftsmen",
    8: "Installation and Machine Operators and Assembly Workers",
    9: "Unskilled Workers",
    10: "Armed Forces Professions",
    90: "Other Situation",
    99: "(blank)",
    101: "Armed Forces Officers",
    102: "Armed Forces Sergeants",
    103: "Other Armed Forces personnel",
    112: "Directors of administrative and commercial services",
    114: "Hotel, catering, trade and other services directors",
    121: "Specialists in physical sciences, mathematics, engineering",
    122: "Health professionals",
    123: "teachers",
    124: "Specialists in finance, accounting, administrative organization, public relations",
    131: "Intermediate level science and engineering technicians and professions",
    132: "Technicians and professionals, intermediate level of health",
    134: "Intermediate level technicians from legal, social, sports, cultural services",
    135: "Information and communication technology technicians",
    141: "Office workers, secretaries, data processing operators",
    143: "Data, accounting, statistical, financial services and registry operators",
    144: "Other administrative support staff",
    151: "personal service workers",
    152: "sellers",
    153: "Personal care workers and the like",
    154: "Protection and security services personnel",
    161: "Market-oriented farmers and skilled agricultural and animal production workers",
    163: "Farmers, livestock keepers, fishermen, hunters and gatherers, subsistence",
    171: "Skilled construction workers and the like, except electricians",
    172: "Skilled workers in metallurgy, metalworking and similar",
    174: "Skilled workers in electricity and electronics",
    175: "Workers in food processing, woodworking, clothing and other industries and crafts",
    181: "Fixed plant and machine operators",
    182: "assembly workers",
    183: "Vehicle drivers and mobile equipment operators",
    192: "Unskilled workers in agriculture, animal production, fisheries and forestry",
    193: "Unskilled workers in extractive industry, construction, manufacturing and transport",
    194: "Meal preparation assistants",
    195: "Street vendors (except food) and street service providers",
}

# Binary flags mapping
YES_NO = {
    1: "yes",
    0: "no",
}

GENDER = {
    1: "male",
    0: "female",
}

# Note: Many other numeric fields (ages, grades, counts, rates, GDP, inflation, unemployment) should remain numeric.
# ---------------------------
# Meta mapping: associate column names to dicts
# ---------------------------

COLUMN_TO_DICT: Dict[str, Dict[Any, str]] = {
    "Marital Status": MARITAL_STATUS,
    "Application mode": APPLICATION_MODE,
    "Course": COURSE,
    "Daytime/evening attendance": DAYTIME_EVENING,
    "Previous qualification": PREVIOUS_QUALIFICATION,
    "Nationality": NATIONALITY,
    "Mother's qualification": MOTHER_QUAL,
    "Father's qualification": FATHER_QUAL,
    "Mother's occupation": MOTHER_OCCUPATION,
    "Father's occupation": FATHER_OCCUPATION,
    "Displaced": DISPLACED,
    "Educational special needs": SPECIAL_NEEDS
    "Debtor": DEBTOR,
    "Tuition fees up to date": FEES_UP_TO_DATE,
    "Scholarship holder": SCHOLARSHIP,
    "International": INTERNATIONAL,
    "Age at enrollment": AGE_AT_ENROLLMENT,
    "Unemployment rate": UNEMPLOYMENT_RATE,
    "Inflation rate": INFLATION_RATE
    "Gender": GENDER,
    # Add more mappings here as needed
}

# ---------------------------
# Translation helpers
# ---------------------------

def translate_value(column: str, value: Any) -> Any:
    """
    Translate a single coded value for a given column name.
    If the column has no mapping defined, returns the original value unchanged.
    If the value is missing (NaN or None), returns None.
    """
    import math

    if value is None:
        return None
    # handle pandas NaN
    try:
        if isinstance(value, float) and math.isnan(value):
            return None
    except Exception:
        pass

    mapping = COLUMN_TO_DICT.get(column)
    if mapping is None:
        # No mapping defined for this column; return value unchanged.
        return value

    # For keys that may be strings in the DataFrame, try to convert to int if possible
    key = value
    if isinstance(value, str):
        # try int conversion
        try:
            key = int(value)
        except Exception:
            # keep as string
            key = value

    # Return mapped label if found; else return a readable fallback
    if key in mapping:
        return mapping[key]
    else:
        # if numeric and mapping absent, return as-is but indicate unknown
        return f"unknown ({value})"


def translate_series(series: pd.Series, column_name: str) -> pd.Series:
    """
    Translate a pandas Series using the mapping for column_name.
    If no mapping exists, returns the original series.
    """
    if column_name not in COLUMN_TO_DICT:
        return series.copy()

    mapping = COLUMN_TO_DICT[column_name]
    # vectorized mapping using map with fallback
    return series.map(lambda v: translate_value(column_name, v))


def translate_dataframe(df: pd.DataFrame, inplace: bool = False) -> pd.DataFrame:
    """
    Translate columns in a DataFrame where mappings exist.

    Params:
        df: pandas DataFrame
        inplace: if True, modifies df in place and returns it; else returns a copy

    Behavior:
        - Columns whose names match keys in COLUMN_TO_DICT will be translated
        - Numeric columns (grades, counts, age, GDP, rates) are left unchanged unless mapping exists
    """
    if not inplace:
        df = df.copy()

    for col in list(df.columns):
        if col in COLUMN_TO_DICT:
            df[col + " (decoded)"] = translate_series(df[col], col)
    return df